### ISSUE TITLE
Having trouble running code with HalfCheetah

### ISSUE THREAD

**Issue by suryabhupa** [ikostrikov/pytorch-naf#5]
I tried running the code with HalfCheetah and commented out the wrappers.Monitor(...) line and any line that rendered the result. I get the error:

Traceback (most recent call last):
  File "main.py", line 98, in <module>
    agent.update_parameters(batch)
  File "/home/sbhupatiraju/pytorch-ddpg-naf/naf.py", line 126, in update_parameters
    loss.backward()
  File "/home/sbhupatiraju/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/sbhupatiraju/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
RuntimeError: element 0 of variables tuple is volatile

Any idea on what might be going on?

**Comment by ikostrikov** [comment]
It looks like there is a problem in with pytorch versions.

Which one are you using?

**Comment by suryabhupa** [comment]
The machine I'm running the code uses version 0.2.0_4. I guess I should try to update to the latest one?

**Comment by ikostrikov** [comment]
Yes, try updating to 0.4.

There might be other problem. I will be able to check only tomorrow.

**Comment by suryabhupa** [comment]
I updated to 0.4, and here's the new problem:

(my_root) sbhupatiraju@instance-11:~/ddpg/pytorch-ddpg-naf$ python main.py
[2018-05-01 16:07:19,958] Making new env: HalfCheetah-v1
/home/sbhupatiraju/ddpg/pytorch-ddpg-naf/ddpg.py:120: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  mu = self.actor((Variable(state, volatile=True)))
/home/sbhupatiraju/ddpg/pytorch-ddpg-naf/ddpg.py:131: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  next_state_batch = Variable(torch.cat(batch.next_state), volatile=True)
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    agent.update_parameters(batch)
  File "/home/sbhupatiraju/ddpg/pytorch-ddpg-naf/ddpg.py", line 146, in update_parameters
    value_loss = MSELoss(state_action_batch, expected_state_action_batch)
  File "/home/sbhupatiraju/.conda/envs/my_root/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sbhupatiraju/.conda/envs/my_root/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 371, in forward
    _assert_no_grad(target)
  File "/home/sbhupatiraju/.conda/envs/my_root/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 12, in _assert_no_grad
    "nn criterions don't compute the gradient w.r.t. targets - please " \
AssertionError: nn criterions don't compute the gradient w.r.t. targets - please mark these tensors as not requiring gradients

**Comment by ikostrikov** [comment]
Yeah. Apparently, one of the recent pytorch updates created a major problem for the repository.

If you need a PyTorch implementation of DDPG I would highly recommend to use this implementation:
https://github.com/sfujim/TD3

**Comment by suryabhupa** [comment]
That codebase also seems to fall prey to a similar issue with criterions; is this an issue with 0.4? Should I rollback to 0.3?

**Comment by ikostrikov** [comment]
Should be fixed in https://github.com/ikostrikov/pytorch-ddpg-naf/commits/master

**Comment by suryabhupa** [comment]
The code works! Is it supposed to be very slow (DDPG, HalfCheetah)?

**Comment by ikostrikov** [comment]
Yeah. It's very slow, since it makes several updates per every simulator step.
